// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwzmyizurlwrtybrvsba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3em15aXp1cmx3cnR5YnJ2c2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDYyMjQsImV4cCI6MjA2MDIyMjIyNH0.kWspS46bpUZq4Os9vrklqTW0Pr5KbebmVe3mkX39YwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);